fix: error during swagger api_docs generation, e.g
drf_yasg.errors.SwaggerGenerationError: Schema for <class 'cms.djangoapps.contentstore.rest_api.v0.serializers.authoring_grading.CourseGradingModelSerializer'> would override distinct serializer <class 'cms.djangoapps.contentstore.rest_api.v1.serializers.grading.CourseGradingModelSerializer'> because they implicitly share the same ref_name; explicitly set the ref_name attribute on both serializers' Meta classes